name: sl-viewer-backend-python
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: "Run unit tests with coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: sevenelevendevunipd/setup-python-ci@v1
        with:
          python-version: "3.10"
          poetry-version: "1.4.1"
          install-dev-deps: true
      - name: Run pytest with coverage
        run: poetry run pytest
      - name: Report coverage 
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
  check_style:
    name: "Check coding style and formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        id: setup
        uses: sevenelevendevunipd/setup-python-ci@v1
        with:
          python-version: "3.10"
          poetry-version: "1.4.1"
          install-dev-deps: true
      - name: Run Black formatter
        run: poetry run black --check .
      - name: Run Ruff linter
        run: poetry run ruff check --format=github .
        if: ${{ success() || (failure() && steps.setup.conclusion == 'success') }}
  docker:
    name: "Build and publish docker image"
    needs: [test, check_style]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/sevenelevendevunipd/sl-viewer-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        if: ${{ !env.ACT }}
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
